### PR TITLE
Fix #4925: Allow users to choose TLS ciphers

### LINKED ISSUE #4925: ssllab result capped to B
### Prerequisites

- [X] I have checked the [Wiki](https://github.com/AdguardTeam/AdGuardHome/wiki) and [Discussions](https://github.com/AdguardTeam/AdGuardHome/discussions) and found no answer

- [X] I have searched other issues and found no duplicates

- [X] I want to report a bug and not ask a question

### Operating system type

Linux, OpenWrt

### CPU architecture

AMD64

### Installation

Docker

### Setup

On one machine

### AdGuard Home version

v0.108.0-b.15

#### What did you do?

SSL Lab test result is `B`

ref : https://blog.qualys.com/product-tech/2018/02/02/forward-secrecy-authenticated-encryption-and-robot-grading-update

Seems like additional config changes at go http listener

#### Screenshots (if applicable)

image

#### Additional information

Reference Article to check : https://www.namecheap.com/support/knowledgebase/article.aspx/9653/38/how-to-check-whether-the-server-supports-forward-secrecy/

tried `openssl s_client -connect example.com:443 -cipher "DHE, EDH"` , the request was failing,

I dont ve idea about these ciphers. I tried for few sites with ssl lab report `A+` the above command was passing

### PR DESCRIPTION
**Pull request by ssrahul96**
Issue https://github.com/AdguardTeam/AdGuardHome/issues/4925

The Cipher `TLS_ECDHE_RSA_WITH_AES_256_CBC_SHA` needs to be supported in order to pass `Forward Secrecy` test of [SSL Labs](https://www.ssllabs.com/ssltest/analyze.html)

SSL Lab result after supporting this Cipher

image

Ref : https://www.namecheap.com/support/knowledgebase/article.aspx/9653/38/how-to-check-whether-the-server-supports-forward-secrecy/

This Cipher is allowed in [d.adguard-dns.com](d.adguard-dns.com) as well, 
SSL Labs report : [link](https://www.ssllabs.com/ssltest/analyze.html?d=d.adguard%2ddns.com&s=94.140.14.49&latest)

### CODE REVIEW

**Comment by ssrahul96** [comment]
fix for https://github.com/AdguardTeam/AdGuardHome/issues/4925

File: internal/aghtls/aghtls.go [hunk 1]
```diff
@@ -28,3 +33,14 @@ func SaferCipherSuites() (safe []uint16) {
 
 	return safe
 }
+
+func UserPreferredCipherSuites(ciphers []string) (userCiphers []uint16) {
```
Comment (ainar-g) [inline internal/aghtls/aghtls.go:37]: 1.  The name of this function isn't really informative.  I feel like a better name would be something like `ParseCipherIDs`.

2.  This function requires documentation.

File: internal/aghtls/aghtls.go [hunk 2]
```diff
@@ -28,3 +33,14 @@ func SaferCipherSuites() (safe []uint16) {
...
+	for _, s := range tls.CipherSuites() {
+		if slices.Contains(ciphers, s.Name) {
+			userCiphers = append(userCiphers, s.ID)
+			log.Debug("user specified cipher : %s, ID : %d", s.Name, s.ID)
+		}
+	}
```
Comment (ainar-g) [inline internal/aghtls/aghtls.go:43]: Currently, this function ignores unknown ciphers, which seems like a mistake.  It should return an informative error instead.

File: internal/dnsforward/config.go [hunk 3]
```diff
@@ -165,6 +165,9 @@ type TLSConfig struct {
 	cert tls.Certificate
 	// DNS names from certificate (SAN) or CN value from Subject
 	dnsNames []string
+
+	// ciphers specified by user
+	TLSCiphers []string `yaml:"tls_ciphers" json:"-"`
```
Comment (ainar-g) [inline internal/dnsforward/config.go:170]: 1.  Please follow the [Go conventions on documenting](https://go.dev/doc/comment).  Unfortunately, a lot of older code doesn't follow them, but we strive to fix that and write all new code with the conventions in mind.

2.  The documentation here should mention that if the slice is empty or nil, the default ciphers are used.

3.  I feel like a better name would communicate that this field should generally not be used.  Something like `override_tls_ciphers`.

File: internal/home/web.go [hunk 4]
```diff
@@ -57,6 +57,9 @@ type webConfig struct {
 	firstRun bool
 
 	serveHTTP3 bool
+
+	// ciphers specified by user
+	tlsCiphers []string
```
Comment (ainar-g) [inline internal/home/web.go:62]: It's better to [parse structured data as soon as possible](https://lexi-lambda.github.io/blog/2019/11/05/parse-don-t-validate/), so it's better to have `[]uint16` here as well.

Also, the documentation should be improved, like in the other cases, and the slice should be moved higher to prevent the structure from having suboptimal field alignment.

**Review by ainar-g — CHANGES_REQUESTED** [review]
1.  Please document the changes in `CHANGELOG.md`.

2.  I don't see the user-overriden ciphers being used in package `dnsforward`.  Is this intentional?

**Comment by ssrahul96** [comment]
> 
This change mainly focused on `http` server only, i am not sure, whether the same is applicable for DOT as well, let me know if its required.

File: internal/aghtls/aghtls.go (hunk 2 above)
Comment (ssrahul96) [reply internal/aghtls/aghtls.go:46]: logged unknown ciphers

File: internal/dnsforward/config.go (hunk 3 above)
Comment (ssrahul96) [reply internal/dnsforward/config.go]: added a function `getTLSCiphers()`

File: internal/aghtls/aghtls.go (hunk 1 above)
Comment (ssrahul96) [reply internal/aghtls/aghtls.go]: changes as per the recommendation

File: internal/home/web.go (hunk 4 above)
Comment (ssrahul96) [reply internal/home/web.go]: changes done

File: CHANGELOG.md [hunk 5]
```diff
@@ -22,9 +22,18 @@ and this project adheres to
...
--->
+[ms-v0.107.16]:   https://github.com/AdguardTeam/AdGuardHome/milestone/52?closed=
+
+### Added
+
+- The new optional `tls.override_tls_ciphers` property list, which can be set in
+  the configuration file.  It allows overriding TLS Ciphers that are used for
+  https listeners ([#4925])
 
+[#4925]: https://github.com/AdguardTeam/AdGuardHome/issues/4925
```
Comment (ainar-g) [inline CHANGELOG.md:33]: New changes are added to the Unreleased section.  Please see the [KeepAChangelog recommendations](https://keepachangelog.com/en/1.0.0/).

File: internal/aghtls/aghtls.go (hunk 2 above)
Comment (ainar-g) [reply internal/aghtls/aghtls.go:46]: Logging is not strict enough.  Please return an error and process it making AGH quit if the user has entered an incorrect cipher ID.

File: internal/aghtls/aghtls.go [hunk 6]
```diff
@@ -28,3 +33,17 @@ func SaferCipherSuites() (safe []uint16) {
 
 	return safe
 }
+
+// ParseCipherIDs returns a set of cipher suites with the cipher names provided
+func ParseCipherIDs(ciphers []string) (userCiphers []uint16) {
+	for _, s := range tls.CipherSuites() {
+		if slices.Contains(ciphers, s.Name) {
+			userCiphers = append(userCiphers, s.ID)
+			log.Debug("user specified cipher : %s, ID : %d", s.Name, s.ID)
```
Comment (ainar-g) [inline internal/aghtls/aghtls.go:42]: I'm not sure that logging belongs in here at all.  It's better to log custom ciphers, if they are present, before parsing them.

File: internal/home/home.go [hunk 7]
```diff
@@ -887,3 +888,16 @@ type jsonError struct {
 	// Message is the error message, an opaque string.
 	Message string `json:"message"`
 }
+
+// getTLSCiphers check for overriden tls ciphers, if the slice is
+// empty, then default safe ciphers are used
+func getTLSCiphers() []uint16 {
+	var cipher []uint16
```
Comment (ainar-g) [inline internal/home/home.go:895]: We prefer to use named returns in such cases.  See the [guidelines item](https://github.com/AdguardTeam/CodeGuidelines/blob/master/Go/Go.md#li-da463e1c).

**Review by ainar-g — CHANGES_REQUESTED** [review]

File: internal/aghtls/aghtls.go (hunk 6 above)
Comment (ainar-g) [reply internal/aghtls/aghtls.go:42]: I think that logging should not be present in what is essentially a general-purpose function.  For some context, the current plan is that most of package `aghtls` will be imported into our `golibs` module one day.

**Comment by ainar-g** [comment]
After looking deeper into it, refactoring of our TLS stuff was required.  It is now done, and your contribution is merged.  Thanks!

**Comment by Harvester57** [comment]
What is the expected format needed to pass to the tls.override_tls_ciphers option ?

**Comment by Harvester57** [comment]
Okay, it is documented in the Wiki, so for those wondering, the option need an array of TLS ciphers. For example:

```
override_tls_ciphers:
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    - TLS_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_RSA_WITH_AES_256_GCM_SHA384
    - TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
    - TLS_ECDHE_ECDSA_WITH_CHACHA20_POLY1305_SHA256
    - TLS_ECDHE_RSA_WITH_CHACHA20_POLY1305_SHA256
```

Available strings are documented in the Go documentation: https://pkg.go.dev/crypto/tls#pkg-constants

Now another question, isn't the server supposed to respect the array order ? This is not the case for the array provided in example, SSL Server Test does return the following:

<html>
<body>


# TLS 1.3 (suites in server-preferred order)
--
TLS_AES_128_GCM_SHA256 (0x1301)   ECDH x25519 (eq. 3072 bits RSA)   FS | 128
TLS_AES_256_GCM_SHA384 (0x1302)   ECDH x25519 (eq. 3072 bits RSA)   FS | 256
TLS_CHACHA20_POLY1305_SHA256 (0x1303)   ECDH x25519 (eq. 3072 bits RSA)   FS | 256P


</body>
</html>

**Comment by ainar-g** [comment]
@Harvester57, the Go implementation of TLS [uses its own automatic ordering](https://go.dev/blog/tls-cipher-suites).

**Comment by Harvester57** [comment]
Thank you for this information ! Makes sens !
